title: Sing Min Hong # your name (or website title) here
logo: "/images/self-photo_circle1.32x1.3.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Life-long Learner.
  <br>
  Tech Enthusiast.
  <br><br>
  <a href="https://www.linkedin.com/in/singminhong/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-135503369-1 # your Google Analytics tracking ID here
